image: node:20.9.0

#cache:
#  paths:
#    - ./pokemon-battle-odds/node_modules/

pages:
  stage: deploy
  script:
    - cd ./pokemon-battle-odds    # enter the React app directory
    - rm -rf build     # remove the existing build
    - CI=false npm install     # install required packages
    - CI=false npm run build
    - cp build/index.html build/404.html     # reroute to index
    - ls
    - cd ..
    - mkdir public
    - ls
    - mv ./pokemon-battle-odds/build/* public
    - export
    - ls
    - echo "Deploying..."
  artifacts:
    paths:
      - public
  tags:
    - Pages
  only:
    - main